default: &default
  adapter: cockroachdb
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 26257

development:
  <<: *default
  database: swapzen_development  # SHARED with swapzen-api
  username: root
  password:
  host: 127.0.0.1

test:
  <<: *default
  database: swapzen_test  # SHARED with swapzen-api
  username: root
  password:
  host: 127.0.0.1

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>  # SHARED cluster
